<?php
/**
 * WordPress import — generated by ORCHESTRAI bricks-compiler / wp-import.js
 * Posts: 17
 * Generated: 2026-05-24
 *
 * Run with:
 *   wp eval-file wp-import-drnl.php --allow-root
 *
 * The script reads post content from wp-import-drnl.json in the same directory.
 * Idempotent: skips any post whose post_name already exists.
 * Sets SEOpress meta: _seopress_titles_title, _seopress_titles_desc,
 *                     _seopress_robots_canonical, _seopress_analysis_target_kw
 */

$json_file = __DIR__ . '/wp-import-drnl.json';

if ( ! file_exists( $json_file ) ) {
    WP_CLI::error( 'JSON file not found: ' . $json_file );
    return;
}

$data = json_decode( file_get_contents( $json_file ), true );

if ( ! $data || empty( $data['posts'] ) ) {
    WP_CLI::error( 'No posts found in ' . basename( $json_file ) );
    return;
}

$total   = count( $data['posts'] );
$created = 0;
$skipped = 0;
$failed  = 0;

WP_CLI::log( "Importing {$total} items from wp-import-drnl.json..." );
WP_CLI::log( "" );

foreach ( $data['posts'] as $i => $post ) {
    $num  = $i + 1;
    $type = $post['post_type'] ?? 'post';
    $slug = $post['post_name'];

    // Skip if slug already exists (works for both posts and pages)
    $existing = get_page_by_path( $slug, OBJECT, $type );
    if ( $existing ) {
        WP_CLI::log( "  [{$num}/{$total}] SKIP (exists as #{$existing->ID}): {$slug}" );
        $skipped++;
        continue;
    }

    // Resolve parent page ID (for hierarchical post types like 'page')
    $parent_id = 0;
    if ( ! empty( $post['parent_slug'] ) ) {
        $parent = get_page_by_path( $post['parent_slug'], OBJECT, $type );
        if ( $parent ) {
            $parent_id = $parent->ID;
        } else {
            WP_CLI::warning( "  Parent not found: '{$post['parent_slug']}' — creating without parent" );
        }
    }

    // Insert post
    $post_id = wp_insert_post( array(
        'post_title'   => wp_slash( $post['post_title'] ),
        'post_name'    => $slug,
        'post_content' => wp_slash( $post['post_content'] ),
        'post_status'  => $post['post_status'] ?? 'draft',
        'post_type'    => $type,
        'post_parent'  => $parent_id,
    ), true );

    if ( is_wp_error( $post_id ) ) {
        WP_CLI::warning( "  [{$num}/{$total}] FAILED: {$slug} — " . $post_id->get_error_message() );
        $failed++;
        continue;
    }

    // Assign category (for post_type = 'post')
    if ( ! empty( $post['category'] ) && $type === 'post' ) {
        $term = get_term_by( 'slug', $post['category'], 'category' );
        if ( $term ) {
            wp_set_post_terms( $post_id, array( $term->term_id ), 'category' );
        } else {
            // Category doesn't exist yet — create it
            $new_term = wp_insert_term(
                ucwords( str_replace( '-', ' ', $post['category'] ) ),
                'category',
                array( 'slug' => $post['category'] )
            );
            if ( ! is_wp_error( $new_term ) ) {
                wp_set_post_terms( $post_id, array( $new_term['term_id'] ), 'category' );
                WP_CLI::log( "  Created category: {$post['category']}" );
            }
        }
    }

    // SEOpress meta fields
    if ( ! empty( $post['seopress_title'] ) ) {
        update_post_meta( $post_id, '_seopress_titles_title', $post['seopress_title'] );
    }
    if ( ! empty( $post['seopress_description'] ) ) {
        update_post_meta( $post_id, '_seopress_titles_desc', $post['seopress_description'] );
    }
    if ( ! empty( $post['seopress_canonical'] ) ) {
        update_post_meta( $post_id, '_seopress_robots_canonical', $post['seopress_canonical'] );
    }
    if ( ! empty( $post['focus_keyword'] ) ) {
        update_post_meta( $post_id, '_seopress_analysis_target_kw', $post['focus_keyword'] );
    }

    $created++;
    WP_CLI::success( "  [{$num}/{$total}] #{$post_id}: " . mb_substr( $post['post_title'], 0, 70 ) );
}

WP_CLI::log( "" );
WP_CLI::log( "Done — Created: {$created} | Skipped (exists): {$skipped} | Failed: {$failed} | Total: {$total}" );
